name: banking_pipeline
version: '1.0.0'
config-version: 2

profile: banking_dbt
  
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  banking_pipeline:
    +catalog: workspace
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  banking_pipeline:
    +file_format: delta
    +header: true

vars:
  bonus_interest_rate: 0.005

flags:
  enable_python: true
